name: Forge Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install library deps
        run: forge install

      - name: Run forge tests
        run: forge test
